FROM apache/airflow:2.8.1-python3.9

USER root
RUN apt-get update && apt-get install -y tini

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

WORKDIR /opt/airflow

ENTRYPOINT ["tini", "--", "airflow"]
CMD ["webserver"]


